# Generated by Django 5.1.5 on 2025-02-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoachingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('type_of_poaching', models.CharField(choices=[('Hunting', 'Hunting'), ('Illegal Fishing', 'Illegal Fishing'), ('Traps', 'Traps')], max_length=50)),
                ('methods_used', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('num_people', models.IntegerField(blank=True, null=True)),
                ('vehicles_boats', models.CharField(blank=True, max_length=255, null=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved')], default='Submitted', max_length=20)),
                ('ap', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
