# Generated by Django 5.1.5 on 2025-03-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_delete_patrolpoachingreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolPoachingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrol_id', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('type_of_poaching', models.CharField(choices=[('Hunting', 'Hunting'), ('Illegal Fishing', 'Illegal Fishing'), ('Traps', 'Traps')], max_length=50)),
                ('methods_used', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('num_people', models.IntegerField(blank=True, null=True)),
                ('vehicles_boats', models.CharField(blank=True, max_length=255, null=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
            ],
        ),
    ]
