# Generated by Django 5.1.5 on 2025-02-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='an',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=200)),
                ('common_habitat', models.TextField()),
                ('lifespan', models.CharField(max_length=100)),
            ],
        ),
    ]
