# Generated by Django 5.1.5 on 2025-03-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AwarenessCarousel',
        ),
    ]
