# Generated by Django 5.1.5 on 2025-03-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('awareness', '0002_delete_awarenesscarousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwarenessCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='carousel_images/')),
                ('image2', models.ImageField(upload_to='carousel_images/')),
                ('image3', models.ImageField(upload_to='carousel_images/')),
                ('image4', models.ImageField(upload_to='carousel_images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
